spring.application.name=backend

# All requests to the backend will be prefixed with /api
spring.mvc.servlet.path=/api

# Database Configuration
spring.datasource.url=jdbc:postgresql://${JDBC_DB_HOST}:${JDBC_DB_PORT}/${JDBC_DB_NAME}
spring.datasource.username=${JDBC_DB_USERNAME}
spring.datasource.password=${JDBC_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Microsoft OAuth2
spring.security.oauth2.client.registration.microsoft.client-id=${MICROSOFT_CLIENT_ID}
spring.security.oauth2.client.registration.microsoft.client-secret=${MICROSOFT_CLIENT_SECRET}
spring.security.oauth2.client.registration.microsoft.scope=openid,profile,email
spring.security.oauth2.client.registration.microsoft.redirect-uri={baseUrl}/api/login/oauth2/code/{registrationId}

spring.security.oauth2.client.provider.microsoft.authorization-uri=https://login.microsoftonline.com/${MICROSOFT_TENANT_ID}/oauth2/v2.0/authorize
spring.security.oauth2.client.provider.microsoft.token-uri=https://login.microsoftonline.com/${MICROSOFT_TENANT_ID}/oauth2/v2.0/token
spring.security.oauth2.client.provider.microsoft.user-info-uri=https://graph.microsoft.com/v1.0/me
spring.security.oauth2.client.provider.microsoft.user-name-attribute=userPrincipalName


# JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# Frontend URL (za CORS i redirect nakon logina)
app.frontend.url=${FRONTEND_URL}

